version: "3.8"

services:

  postgres-db:
    container_name: neon_ark_creature_db
    image: postgres:16
    restart: always

    environment:
      POSTGRES_USER: neonark
      POSTGRES_PASSWORD: neonarkpass
      POSTGRES_DB: neonark_creatures
      POSTGRES_HOST_AUTH_METHOD: password

    ports:
      - "5436:5432"

    volumes:
      - neonark_creature_pgdata:/var/lib/postgresql/dat

volumes:
  neonark_creature_pgdata:
    driver: local